name: adding more steps to the workflow
on:
    push:
        branches:
           - master  
jobs:
    lint-job:
        steps:
           - name: Checkout the code
             uses: actions/checkout@v3
           - name: Install Dependencies
             run: npm ci
            
    